### ISSUE TITLE
cenote-taker2 error

### ISSUE THREAD

**Issue by mabouelk** [sunbeam-labs/sbx_virus_id#2]
Hello, 

I run sunbeam on Linux but  I got this message"run_cenote-taker2.py: error: argument --cenote-dbs: expected one argument
/home/exouser/Downloads/extensions/sbx_virus_id/Cenote-Taker2
[Tue Jan  2 13:24:55 2024]
Error in rule cenote_taker2:
    jobid: 4
    input: /home/exouser/nov-1882/sunbeam_output/assembly/virus_id_megahit/1882_S1_L001_asm/final.contigs.fa, /home/exouser/nov-1882/sunbeam_output/virus/cenote_taker2/.installed
    output: /home/exouser/nov-1882/sunbeam_output/virus/cenote_taker2/1882_S1_L001/final.contigs.fasta, /home/exouser/nov-1882/sunbeam_output/virus/cenote_taker2/1882_S1_L001/1882_S1_L001/1882_S1_L001_CONTIG_SUMMARY.tsv
    log: /home/exouser/nov-1882/sunbeam_output/logs/cenote_taker2_1882_S1_L001.log (check log file(s) for error details)
    conda-env: /home/exouser/Downloads/.snakemake/38bf06c8bbddf433a2619021d39ca850_
    shell:
        
        if [[ 1882_S1_L001 == *"."* ]]; then
            echo "CenoteTaker2 doesn't allow sample names with '.' in them"
            exit 1
        fi

        cd /home/exouser/nov-1882/sunbeam_output/virus/cenote_taker2
        mkdir -p 1882_S1_L001
        cd 1882_S1_L001
        
        python /home/exouser/Downloads/extensions/sbx_virus_id/Cenote-Taker2/run_cenote-taker2.py -c /home/exouser/nov-1882/sunbeam_output/assembly/virus_id_megahit/1882_S1_L001_asm/final.contigs.fa -r 1882_S1_L001 -m 32 -t 32 -p true -db virion --cenote-dbs  2>&1 | tee /home/exouser/nov-1882/sunbeam_output/logs/cenote_taker2_1882_S1_L001.log
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Sunbeam failed with error.
Complete log: .snakemake/log/2024-01-02T082408.199838.snakemake.log
"

**Comment by Ulthran** [comment]
Hi @mabouelk, it looks like you probably didn't fill in the cenote database path in sunbeam_config.yml.

**Comment by mabouelk** [comment]
Thank you so much! it worked! 
but I got another error I beleive it could be a database path but I can't find it 

dirname: missing operand
Try 'dirname --help' for more information.
basename: missing operand
Try 'basename --help' for more information.
USAGE
  blastx [-h] [-help] [-import_search_strategy filename]
    [-export_search_strategy filename] [-task task_name] [-db database_name]
    [-dbsize num_letters] [-gilist filename] [-seqidlist filename]
    [-negative_gilist filename] [-negative_seqidlist filename]
    [-taxids taxids] [-negative_taxids taxids] [-taxidlist filename]
    [-negative_taxidlist filename] [-ipglist filename]
    [-negative_ipglist filename] [-entrez_query entrez_query]
    [-db_soft_mask filtering_algorithm] [-db_hard_mask filtering_algorithm]
    [-subject subject_input_file] [-subject_loc range] [-query input_file]
    [-out output_file] [-evalue evalue] [-word_size int_value]
    [-gapopen open_penalty] [-gapextend extend_penalty]
    [-qcov_hsp_perc float_value] [-max_hsps int_value]
    [-xdrop_ungap float_value] [-xdrop_gap float_value]
    [-xdrop_gap_final float_value] [-searchsp int_value]
    [-sum_stats bool_value] [-max_intron_length length] [-seg SEG_options]
    [-soft_masking soft_masking] [-matrix matrix_name]
    [-threshold float_value] [-culling_limit int_value]
    [-best_hit_overhang float_value] [-best_hit_score_edge float_value]
    [-subject_besthit] [-window_size int_value] [-ungapped] [-lcase_masking]
    [-query_loc range] [-strand strand] [-parse_deflines]
    [-query_gencode int_value] [-outfmt format] [-show_gis]
    [-num_descriptions int_value] [-num_alignments int_value]
    [-line_length line_length] [-html] [-sorthits sort_hits]
    [-sorthsps sort_hsps] [-max_target_seqs num_sequences]
    [-num_threads int_value] [-mt_mode int_value] [-remote]
    [-comp_based_stats compo] [-use_sw_tback] [-version]

DESCRIPTION
   Translated Query-Protein Subject BLAST 2.14.1+

Use '-help' to print detailed descriptions of command line arguments
========================================================================

Error: Too many positional arguments (1), the offending value: 6
Error:  (CArgException::eSynopsis) Too many positional arguments (1), the offending value: 6
[Tue Jan  2 18:43:44 2024]
Error in rule virus_blastx:
    jobid: 1
    input: /home/exouser/nov-1882/sunbeam_output/virus/final_1882_S1_L001_contigs.fasta
    output: /home/exouser/nov-1882/sunbeam_output/virus/blastx/1882_S1_L001.btf
    log: /home/exouser/nov-1882/sunbeam_output/logs/run_virus_blastx_1882_S1_L001.log (check log file(s) for error details)
    conda-env: /home/exouser/Downloads/.snakemake/4b7f455816a0af391b2f98c21de3efa3_
    shell:
        
        if [ -s /home/exouser/nov-1882/sunbeam_output/virus/final_1882_S1_L001_contigs.fasta ]; then
            export BLASTDB=$(dirname )
            blastx             -query /home/exouser/nov-1882/sunbeam_output/virus/final_1882_S1_L001_contigs.fasta             -db $(basename )             -outfmt 6             -num_threads 4             -evalue 0.05             -max_target_seqs 100             -out /home/exouser/nov-1882/sunbeam_output/virus/blastx/1882_S1_L001.btf             2>&1 | tee /home/exouser/nov-1882/sunbeam_output/logs/run_virus_blastx_1882_S1_L001.log
        else
            echo "Caught empty query" >> /home/exouser/nov-1882/sunbeam_output/logs/run_virus_blastx_1882_S1_L001.log
            touch /home/exouser/nov-1882/sunbeam_output/virus/blastx/1882_S1_L001.btf
        fi
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Sunbeam failed with error.
No benchmark files found
Complete log: .snakemake/log/2024-01-02T184342.492850.snakemake.log

**Comment by Ulthran** [comment]
Did you define the `blast_db` path in the config as well?

**Comment by mabouelk** [comment]
I downloaded it but I can't find it anywhere. Where it should be located?
Thank you again

**Comment by Ulthran** [comment]
Did you follow the instructions in the README to download the blast db?

**Comment by mabouelk** [comment]
Yes, I did. I don't know what else I can do to complete the run. Any guidance would be appreciated!

**Comment by Ulthran** [comment]
It should be in a directory called `viral_prot` or `refseq_select_prot`, whatever you named it when you created it. And those directories should be in whatever directory you were in when you went through the process detailed in the readme.

**Comment by mabouelk** [comment]
Yes I do have these directories and I specified them but no luck. see below

sbx_virus_id:
  blast_db: '/home/exouser/refseq_select_prot/viral_prot'
  blastx_threads: 4
  bowtie2_build_threads: 4
  cenote_taker2_db: '/home/exouser/Downloads/extensions/sbx_virus_id/Cenote-Taker2'
  host_decontam: true
  include_phages: false
  use_spades: false
  use_virsorter: false
  virsorter_db: ''
sbx_virus_id:
  blast_db: ''
  blastx_threads: 4
  bowtie2_build_threads: 4
  cenote_taker2_db: ''
  virsorter_db: ''
  host_decontam: True
  include_phages: False
  use_spades: False # Default: Megahit
  use_virsorter: False # Default: Cenote-Taker2

**Comment by Ulthran** [comment]
What's the error with `blast_db` specified?

**Comment by mabouelk** [comment]
Activating conda environment: ../Downloads/.snakemake/4b7f455816a0af391b2f98c21de3efa3_
dirname: missing operand
Try 'dirname --help' for more information.
basename: missing operand
Try 'basename --help' for more information.
USAGE
  blastx [-h] [-help] [-import_search_strategy filename]
    [-export_search_strategy filename] [-task task_name] [-db database_name]
    [-dbsize num_letters] [-gilist filename] [-seqidlist filename]
    [-negative_gilist filename] [-negative_seqidlist filename]
    [-taxids taxids] [-negative_taxids taxids] [-taxidlist filename]
    [-negative_taxidlist filename] [-ipglist filename]
    [-negative_ipglist filename] [-entrez_query entrez_query]
    [-db_soft_mask filtering_algorithm] [-db_hard_mask filtering_algorithm]
    [-subject subject_input_file] [-subject_loc range] [-query input_file]
    [-out output_file] [-evalue evalue] [-word_size int_value]
    [-gapopen open_penalty] [-gapextend extend_penalty]
    [-qcov_hsp_perc float_value] [-max_hsps int_value]
    [-xdrop_ungap float_value] [-xdrop_gap float_value]
    [-xdrop_gap_final float_value] [-searchsp int_value]
    [-sum_stats bool_value] [-max_intron_length length] [-seg SEG_options]
    [-soft_masking soft_masking] [-matrix matrix_name]
    [-threshold float_value] [-culling_limit int_value]
    [-best_hit_overhang float_value] [-best_hit_score_edge float_value]
    [-subject_besthit] [-window_size int_value] [-ungapped] [-lcase_masking]
    [-query_loc range] [-strand strand] [-parse_deflines]
    [-query_gencode int_value] [-outfmt format] [-show_gis]
    [-num_descriptions int_value] [-num_alignments int_value]
    [-line_length line_length] [-html] [-sorthits sort_hits]
    [-sorthsps sort_hsps] [-max_target_seqs num_sequences]
    [-num_threads int_value] [-mt_mode int_value] [-remote]
    [-comp_based_stats compo] [-use_sw_tback] [-version]

DESCRIPTION
   Translated Query-Protein Subject BLAST 2.14.1+

Use '-help' to print detailed descriptions of command line arguments
========================================================================

Error: Too many positional arguments (1), the offending value: 6
Error:  (CArgException::eSynopsis) Too many positional arguments (1), the offending value: 6
[Wed Jan  3 19:32:27 2024]
Error in rule virus_blastx:
    jobid: 1
    input: /home/exouser/nov-1882/sunbeam_output/virus/final_1882_S1_L001_contigs.fasta
    output: /home/exouser/nov-1882/sunbeam_output/virus/blastx/1882_S1_L001.btf
    log: /home/exouser/nov-1882/sunbeam_output/logs/run_virus_blastx_1882_S1_L001.log (check log file(s) for error details)
    conda-env: /home/exouser/Downloads/.snakemake/4b7f455816a0af391b2f98c21de3efa3_
    shell:
        
        if [ -s /home/exouser/nov-1882/sunbeam_output/virus/final_1882_S1_L001_contigs.fasta ]; then
            export BLASTDB=$(dirname )
            blastx             -query /home/exouser/nov-1882/sunbeam_output/virus/final_1882_S1_L001_contigs.fasta             -db $(basename )             -outfmt 6             -num_threads 4             -evalue 0.05             -max_target_seqs 100             -out /home/exouser/nov-1882/sunbeam_output/virus/blastx/1882_S1_L001.btf             2>&1 | tee /home/exouser/nov-1882/sunbeam_output/logs/run_virus_blastx_1882_S1_L001.log
        else
            echo "Caught empty query" >> /home/exouser/nov-1882/sunbeam_output/logs/run_virus_blastx_1882_S1_L001.log
            touch /home/exouser/nov-1882/sunbeam_output/virus/blastx/1882_S1_L001.btf
        fi
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Sunbeam failed with error.
No benchmark files found
Complete log: .snakemake/log/2024-01-03T193225.999023.snakemake.log

**Comment by Ulthran** [comment]
It still looks like that parameter isn't defined... Can you include the full `sunbeam_config.yml` for this project?

**Comment by mabouelk** [comment]
Sure 

```
all:
  output_fp: sunbeam_output
  paired_end: true
  root: /home/exouser/nov-1882
  samplelist_fp: samples.csv
  version: 4.1.0
annotation:
  suffix: annotation
assembly:
  suffix: assembly
benchmarks:
  suffix: benchmarks
blastdbs:
  root_fp: ''
classify:
  suffix: classify
logs:
  suffix: logs
mapping:
  suffix: mapping
qc:
  adapter_template: $CONDA_PREFIX/share/trimmomatic/adapters/NexteraPE-PE.fa
  cutadapt_opts: --discard-trimmed
  frac: 0.6
  fwd_adapters:
  - GTTTCCCAGTCACGATC
  - GTTTCCCAGTCACGATCNNNNNNNNNGTTTCCCAGTCACGATC
  host_fp: ''
  kz_threshold: 0.55
  leading: 3
  minlen: 36
  pct_id: 0.5
  rev_adapters:
  - GTTTCCCAGTCACGATC
  - GTTTCCCAGTCACGATCNNNNNNNNNGTTTCCCAGTCACGATC
  slidingwindow:
  - 4
  - 15
  suffix: qc
  trailing: 3
sbx_annotation:
  circular_kmax: 1000
  circular_kmin: 10
  circular_min_len: 3500
  threads: 4
sbx_assembly:
  min_length: 300
sbx_coverage:
  threads: 4
sbx_kraken:
  kraken_db_fp: ''
sbx_virus_id:
  blast_db: '/home/exouser/refseq_select_prot/viral_prot'
  blastx_threads: 4
  bowtie2_build_threads: 4
  cenote_taker2_db: '/home/exouser/Downloads/extensions/sbx_virus_id/Cenote-Taker2'
  host_decontam: true
  include_phages: false
  use_spades: false
  use_virsorter: false
  virsorter_db: ''
sbx_virus_id:
  blast_db: ''
  blastx_threads: 4
  bowtie2_build_threads: 4
  cenote_taker2_db: ''
  virsorter_db: ''
  host_decontam: True
  include_phages: False
  use_spades: False # Default: Megahit
  use_virsorter: False # Default: Cenote-Taker2
```

**Comment by Ulthran** [comment]
OK yea the problem is that the `sbx_virus_id` section got doubled somehow. Remove the last one so that this:

```
sbx_virus_id:
  blast_db: '/home/exouser/refseq_select_prot/viral_prot'
  blastx_threads: 4
  bowtie2_build_threads: 4
  cenote_taker2_db: '/home/exouser/Downloads/extensions/sbx_virus_id/Cenote-Taker2'
  host_decontam: true
  include_phages: false
  use_spades: false
  use_virsorter: false
  virsorter_db: ''
sbx_virus_id:
  blast_db: ''
  blastx_threads: 4
  bowtie2_build_threads: 4
  cenote_taker2_db: ''
  virsorter_db: ''
  host_decontam: True
  include_phages: False
  use_spades: False # Default: Megahit
  use_virsorter: False # Default: Cenote-Taker2
```

becomes this:

```
sbx_virus_id:
  blast_db: '/home/exouser/refseq_select_prot/viral_prot'
  blastx_threads: 4
  bowtie2_build_threads: 4
  cenote_taker2_db: '/home/exouser/Downloads/extensions/sbx_virus_id/Cenote-Taker2'
  host_decontam: true
  include_phages: false
  use_spades: false
  use_virsorter: false
  virsorter_db: ''
```
